CREATE TABLE Clientes (
    ID_CLIENTE VARCHAR(5) PRIMARY KEY NOT NULL,
     NOMBRE VARCHAR(10) NOT NULL,
     APELLIDOS VARCHAR(23) NOT NULL,
     E_MAIL VARCHAR(25) NOT NULL,
     TELEFONO VARCHAR(15) NOT NULL,
     DOMICILIO VARCHAR(70) NOT NULL
);

CREATE TABLE Empleados (
    ID_EMPLEADO VARCHAR(5) PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(10) NOT NULL,
    APELLIDO VARCHAR(23) NOT NULL,
    DOMICILIO VARCHAR(70) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    CORREO VARCHAR(25) NOT NULL,
    CARGO VARCHAR(13) NOT NULL
);

CREATE TABLE Proveedores (
    ID_PROVEEDOR VARCHAR(5) UNIQUE NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(10) NOT NULL,
    APELLIDOS VARCHAR(23) NOT NULL,
    ESTADO VARCHAR(14) NOT NULL,
    DOMICILIO VARCHAR(70) NOT NULL,
    TELEFONO NUMERIC NOT NULL,
    EMPRESA VARCHAR(13) NOT NULL
);
